import type { Course } from "@/types/course"

export const MOCK_COURSES: Course[] = [
  {
    id: "1",
    title: "Khóa Học Tiếng Anh Giao Tiếp Cùng Giáo Viên Bản Xứ",
    instructor: "Cô Sarah Johnson",
    price: 799000,
    originalPrice: 1200000,
    image: "/hoc-tieng-anh-giao-tiep.jpg",
    description: "Thành thạo tiếng Anh giao tiếp với giáo viên người Mỹ qua các bài học tương tác",
    fullDescription:
      "Khóa học tiếng Anh giao tiếp toàn diện được thiết kế để giúp bạn đạt được sự lưu loát thông qua việc tương tác trực tiếp với giáo viên người Mỹ bản xứ. Bạn sẽ học cách phát âm tự nhiên, các cách diễn đạt hàng ngày và xây dựng sự tự tin trong các cuộc hội thoại thực tế. Khóa học bao gồm hơn 50 video bài giảng, các buổi thực hành trực tiếp và phản hồi cá nhân hóa.",
    rating: 4.8,
    students: 2847,
    duration: "12 tuần",
    level: "Từ cơ bản đến nâng cao",
    category: "Ngoại ngữ",
    tags: ["Tiếng Anh", "Giao tiếp", "Giáo viên bản xứ", "Hội thoại"],
    isFavorite: false,
  },
  {
    id: "2",
    title: "Bootcamp Lập Trình Web - React & Node.js",
    instructor: "Thầy David Chen",
    price: 1500000,
    originalPrice: 2000000,
    image: "react.jpg",
    description: "Khóa học lập trình web full-stack bao gồm React, Node.js và các công cụ hiện đại",
    fullDescription:
      "Trở thành lập trình viên full-stack với bootcamp toàn diện này. Học React cho frontend, Node.js cho backend, quản lý cơ sở dữ liệu và chiến lược triển khai. Xây dựng 5 dự án thực tế và có được kỹ năng sẵn sàng cho công việc. Bao gồm quyền truy cập trọn đời và hỗ trợ nghề nghiệp.",
    rating: 4.9,
    students: 1523,
    duration: "16 tuần",
    level: "Trung cấp",
    category: "Lập trình",
    tags: ["React", "Node.js", "JavaScript", "Full-stack"],
    isFavorite: false,
  },
  {
    id: "3",
    title: "Thành Thạo Digital Marketing 2024",
    instructor: "Cô Maria Rodriguez",
    price: 899000,
    image: "maketing.jpg",
    description: "Khóa học marketing số hoàn chỉnh bao gồm SEO, mạng xã hội và quảng cáo trả phí",
    fullDescription:
      "Thành thạo digital marketing với đào tạo thực hành về SEO, Google Ads, Facebook Marketing, chiến lược nội dung và phân tích dữ liệu. Học từ các nghiên cứu tình huống thực tế và xây dựng chiến dịch marketing của riêng bạn. Hoàn hảo cho doanh nhân và chuyên gia marketing.",
    rating: 4.7,
    students: 3241,
    duration: "10 tuần",
    level: "Cơ bản",
    category: "Marketing",
    tags: ["SEO", "Mạng xã hội", "Google Ads", "Content Marketing"],
    isFavorite: false,
  },
  {
    id: "4",
    title: "Python cho Khoa Học Dữ Liệu & AI",
    instructor: "TS. James Wilson",
    price: 1200000,
    image: "python.jpg",
    description: "Học lập trình Python cho phân tích dữ liệu, machine learning và ứng dụng AI",
    fullDescription:
      "Đi sâu vào Python cho khoa học dữ liệu và trí tuệ nhân tạo. Bao gồm pandas, numpy, matplotlib, scikit-learn và TensorFlow. Làm việc với các bộ dữ liệu thực tế và xây dựng mô hình ML. Bao gồm chứng chỉ khi hoàn thành.",
    rating: 4.6,
    students: 1876,
    duration: "14 tuần",
    level: "Trung cấp",
    category: "Khoa học dữ liệu",
    tags: ["Python", "Machine Learning", "AI", "Phân tích dữ liệu"],
    isFavorite: false,
  },
  {
    id: "5",
    title: "Cơ Bản Thiết Kế Đồ Họa",
    instructor: "Cô Emma Thompson",
    price: 650000,
    image: "đồ-họa.jpg",
    description: "Thành thạo các nguyên tắc cơ bản của thiết kế đồ họa sử dụng Adobe Creative Suite",
    fullDescription:
      "Học các nguyên tắc cơ bản của thiết kế đồ họa sử dụng Photoshop, Illustrator và InDesign. Hiểu về lý thuyết màu sắc, typography, nguyên tắc bố cục và thiết kế nhận diện thương hiệu. Tạo portfolio chuyên nghiệp với hơn 10 dự án.",
    rating: 4.5,
    students: 2156,
    duration: "8 tuần",
    level: "Cơ bản",
    category: "Thiết kế",
    tags: ["Photoshop", "Illustrator", "Thiết kế", "Sáng tạo"],
    isFavorite: false,
  },
  {
    id: "6",
    title: "Chiến Lược Kinh Doanh & Lãnh Đạo",
    instructor: "Thầy Michael Brown",
    price: 1100000,
    image: "kd.jpg",
    description: "Phát triển tư duy chiến lược và kỹ năng lãnh đạo cho thành công trong kinh doanh",
    fullDescription:
      "Nâng cao hiểu biết kinh doanh của bạn với lập kế hoạch chiến lược, lãnh đạo nhóm và khung ra quyết định. Học từ các tình huống kinh doanh thực tế và phát triển kế hoạch chiến lược của riêng bạn. Lý tưởng cho các nhà quản lý và doanh nhân.",
    rating: 4.8,
    students: 987,
    duration: "12 tuần",
    level: "Nâng cao",
    category: "Kinh doanh",
    tags: ["Chiến lược", "Lãnh đạo", "Quản lý", "Kinh doanh"],
    isFavorite: false,
  },
  // Khóa học dưới 500.000 VNĐ
  {
    id: "13",
    title: "HTML & CSS Cơ Bản cho Người Mới",
    instructor: "Thầy Nguyễn Văn A",
    price: 299000,
    originalPrice: 450000,
    image: "html.jpg",
    description: "Học HTML và CSS từ con số 0, xây dựng website đầu tiên của bạn",
    fullDescription:
      "Khóa học dành cho người hoàn toàn mới bắt đầu với lập trình web. Học cách tạo trang web với HTML và CSS, hiểu về cấu trúc trang web, styling và responsive design. Bao gồm 5 dự án thực hành và hỗ trợ trực tuyến.",
    rating: 4.6,
    students: 3456,
    duration: "6 tuần",
    level: "Cơ bản",
    category: "Lập trình",
    tags: ["HTML", "CSS", "Web", "Responsive"],
    isFavorite: false,
  },
  {
    id: "14",
    title: "Tiếng Anh Cơ Bản A1-A2",
    instructor: "Cô Lê Thị B",
    price: 399000,
    originalPrice: 600000,
    image: "a1.jpg",
    description: "Khóa học tiếng Anh cơ bản từ A1 lên A2 với phương pháp học hiện đại",
    fullDescription:
      "Khóa học tiếng Anh cơ bản được thiết kế cho người mới bắt đầu. Học từ vựng cơ bản, ngữ pháp căn bản và kỹ năng giao tiếp hàng ngày. Bao gồm 100+ bài học video, bài tập tương tác và kiểm tra định kỳ.",
    rating: 4.4,
    students: 5678,
    duration: "8 tuần",
    level: "Cơ bản",
    category: "Ngoại ngữ",
    tags: ["Tiếng Anh", "A1", "A2", "Cơ bản"],
    isFavorite: false,
  },
  {
    id: "15",
    title: "Excel Cơ Bản đến Nâng Cao",
    instructor: "Thầy Trần Văn C",
    price: 349000,
    originalPrice: 500000,
    image: "e.jpg",
    description: "Thành thạo Excel từ cơ bản đến nâng cao, công thức và pivot table",
    fullDescription:
      "Học Excel từ những kiến thức cơ bản nhất đến các kỹ thuật nâng cao. Bao gồm công thức, hàm, pivot table, biểu đồ và macro. Phù hợp cho nhân viên văn phòng và sinh viên.",
    rating: 4.7,
    students: 4321,
    duration: "5 tuần",
    level: "Từ cơ bản đến nâng cao",
    category: "Kinh doanh",
    tags: ["Excel", "Công thức", "Pivot Table", "Văn phòng"],
    isFavorite: false,
  },
  {
    id: "16",
    title: "Photoshop Cơ Bản cho Người Mới",
    instructor: "Cô Phạm Thị D",
    price: 450000,
    originalPrice: 650000,
    image: "",
    description: "Học Photoshop từ đầu, chỉnh sửa ảnh và thiết kế đồ họa cơ bản",
    fullDescription:
      "Khóa học Photoshop dành cho người mới bắt đầu. Học cách sử dụng các công cụ cơ bản, chỉnh sửa ảnh, tạo poster và banner đơn giản. Bao gồm 50+ bài học thực hành và template miễn phí.",
    rating: 4.5,
    students: 2987,
    duration: "6 tuần",
    level: "Cơ bản",
    category: "Thiết kế",
    tags: ["Photoshop", "Chỉnh sửa ảnh", "Thiết kế", "Adobe"],
    isFavorite: false,
  },
  {
    id: "17",
    title: "Facebook Marketing cho Doanh Nghiệp Nhỏ",
    instructor: "Thầy Hoàng Văn E",
    price: 399000,
    image: "maketing.jpg",
    description: "Học cách quảng cáo hiệu quả trên Facebook cho doanh nghiệp nhỏ",
    fullDescription:
      "Khóa học Facebook Marketing chuyên sâu cho chủ doanh nghiệp nhỏ. Học cách tạo fanpage, chạy quảng cáo, target khách hàng và đo lường hiệu quả. Bao gồm case study thực tế và template quảng cáo.",
    rating: 4.6,
    students: 1876,
    duration: "4 tuần",
    level: "Cơ bản",
    category: "Marketing",
    tags: ["Facebook", "Quảng cáo", "SMM", "Doanh nghiệp nhỏ"],
    isFavorite: false,
  },
  {
    id: "18",
    title: "Kỹ Năng Thuyết Trình Chuyên Nghiệp",
    instructor: "Cô Vũ Thị F",
    price: 299000,
    image: "canvay.jpg",
    description: "Phát triển kỹ năng thuyết trình và giao tiếp trước đám đông",
    fullDescription:
      "Khóa học giúp bạn tự tin thuyết trình trước đám đông. Học cách chuẩn bị nội dung, sử dụng body language, xử lý câu hỏi khó và tạo slide hiệu quả. Bao gồm thực hành và feedback cá nhân.",
    rating: 4.8,
    students: 2345,
    duration: "3 tuần",
    level: "Cơ bản",
    category: "Kinh doanh",
    tags: ["Thuyết trình", "Giao tiếp", "Kỹ năng mềm", "Presentation"],
    isFavorite: false,
  },
  {
    id: "19",
    title: "WordPress Cơ Bản - Tạo Website Không Cần Code",
    instructor: "Thầy Đặng Văn G",
    price: 449000,
    originalPrice: 650000,
    image: "w.jpg",
    description: "Tạo website chuyên nghiệp với WordPress mà không cần biết lập trình",
    fullDescription:
      "Học cách tạo website với WordPress từ A-Z. Bao gồm cài đặt, chọn theme, tùy chỉnh giao diện, thêm nội dung và plugin. Phù hợp cho doanh nghiệp nhỏ và cá nhân muốn có website riêng.",
    rating: 4.5,
    students: 3210,
    duration: "5 tuần",
    level: "Cơ bản",
    category: "Lập trình",
    tags: ["WordPress", "Website", "CMS", "No-code"],
    isFavorite: false,
  },
  {
    id: "20",
    title: "Tiếng Trung Cơ Bản HSK 1-2",
    instructor: "Cô Nguyễn Thị H",
    price: 399000,
    originalPrice: 580000,
    image: "kt.jpg",
    description: "Học tiếng Trung từ cơ bản, chuẩn bị cho kỳ thi HSK 1-2",
    fullDescription:
      "Khóa học tiếng Trung cơ bản theo chuẩn HSK. Học phát âm, từ vựng, ngữ pháp và kỹ năng giao tiếp cơ bản. Bao gồm 150+ từ vựng HSK 1-2 và bài tập luyện thi.",
    rating: 4.3,
    students: 1654,
    duration: "10 tuần",
    level: "Cơ bản",
    category: "Ngoại ngữ",
    tags: ["Tiếng Trung", "HSK", "Mandarin", "Cơ bản"],
    isFavorite: false,
  },
  {
    id: "21",
    title: "Kế Toán Cơ Bản cho Doanh Nghiệp Nhỏ",
    instructor: "Thầy Lý Văn I",
    price: 349000,
    image: "kt.jpg",
    description: "Học kế toán cơ bản, quản lý tài chính cho doanh nghiệp nhỏ",
    fullDescription:
      "Khóa học kế toán cơ bản dành cho chủ doanh nghiệp nhỏ. Học cách ghi sổ, lập báo cáo tài chính, quản lý dòng tiền và thuế. Bao gồm template Excel và phần mềm kế toán miễn phí.",
    rating: 4.6,
    students: 2876,
    duration: "6 tuần",
    level: "Cơ bản",
    category: "Kinh doanh",
    tags: ["Kế toán", "Tài chính", "Doanh nghiệp nhỏ", "Thuế"],
    isFavorite: false,
  },
  {
    id: "22",
    title: "Canva Design - Thiết Kế Đồ Họa Dễ Dàng",
    instructor: "Cô Bùi Thị J",
    price: 249000,
    originalPrice: 400000,
    image: "canvay.jpg",
    description: "Tạo thiết kế đẹp mắt với Canva cho social media và marketing",
    fullDescription:
      "Học cách sử dụng Canva để tạo poster, banner, post social media chuyên nghiệp. Bao gồm nguyên tắc thiết kế, color theory và typography. Phù hợp cho marketer và chủ doanh nghiệp.",
    rating: 4.7,
    students: 4567,
    duration: "3 tuần",
    level: "Cơ bản",
    category: "Thiết kế",
    tags: ["Canva", "Social Media", "Poster", "Banner"],
    isFavorite: false,
  },
  {
    id: "23",
    title: "Python Cơ Bản cho Người Mới",
    instructor: "Thầy Cao Văn K",
    price: 399000,
    originalPrice: 600000,
    image: "w.jpg",
    description: "Học lập trình Python từ con số 0, ngôn ngữ dễ học nhất",
    fullDescription:
      "Khóa học Python cơ bản dành cho người chưa biết lập trình. Học syntax, biến, hàm, vòng lặp và xử lý dữ liệu cơ bản. Bao gồm 10+ project nhỏ và hướng dẫn cài đặt môi trường.",
    rating: 4.8,
    students: 3789,
    duration: "8 tuần",
    level: "Cơ bản",
    category: "Lập trình",
    tags: ["Python", "Programming", "Cơ bản", "Beginner"],
    isFavorite: false,
  },
  {
    id: "24",
    title: "Google Ads Cơ Bản - Quảng Cáo Hiệu Quả",
    instructor: "Cô Đinh Thị L",
    price: 449000,
    image: "e.jpg",
    description: "Học cách chạy quảng cáo Google Ads hiệu quả với ngân sách nhỏ",
    fullDescription:
      "Khóa học Google Ads từ cơ bản đến thực chiến. Học cách setup campaign, chọn keyword, viết ad copy và tối ưu hóa chi phí. Bao gồm case study thực tế và template campaign.",
    rating: 4.5,
    students: 2134,
    duration: "5 tuần",
    level: "Cơ bản",
    category: "Marketing",
    tags: ["Google Ads", "PPC", "SEM", "Quảng cáo"],
    isFavorite: false,
  },
  {
    id: "25",
    title: "Tiếng Nhật Cơ Bản N5",
    instructor: "Cô Tanaka Yuki",
    price: 499000,
    originalPrice: 750000,
    image: "n5.jpg",
    description: "Học tiếng Nhật từ cơ bản, chuẩn bị cho kỳ thi JLPT N5",
    fullDescription:
      "Khóa học tiếng Nhật cơ bản theo chuẩn JLPT N5. Học Hiragana, Katakana, từ vựng và ngữ pháp cơ bản. Bao gồm 300+ từ vựng N5 và bài tập luyện thi với giáo viên người Nhật.",
    rating: 4.6,
    students: 1987,
    duration: "12 tuần",
    level: "Cơ bản",
    category: "Ngoại ngữ",
    tags: ["Tiếng Nhật", "JLPT", "N5", "Hiragana"],
    isFavorite: false,
  },
  {
    id: "26",
    title: "Video Editing với DaVinci Resolve",
    instructor: "Thầy Phạm Văn M",
    price: 399000,
    image: "edit.jpg",
    description: "Học edit video chuyên nghiệp với phần mềm miễn phí DaVinci Resolve",
    fullDescription:
      "Khóa học edit video với DaVinci Resolve - phần mềm miễn phí mạnh mẽ. Học cách cắt ghép, color grading, hiệu ứng và xuất video chất lượng cao. Phù hợp cho YouTuber và content creator.",
    rating: 4.7,
    students: 2456,
    duration: "6 tuần",
    level: "Cơ bản",
    category: "Thiết kế",
    tags: ["Video Editing", "DaVinci Resolve", "YouTube", "Content"],
    isFavorite: false,
  },
  {
    id: "27",
    title: "Kỹ Năng Bán Hàng Online",
    instructor: "Cô Hoàng Thị N",
    price: 299000,
    image: "maketing.jpg",
    description: "Phát triển kỹ năng bán hàng online, tăng doanh số trên các platform",
    fullDescription:
      "Khóa học kỹ năng bán hàng online toàn diện. Học cách viết content bán hàng, chăm sóc khách hàng, xử lý phản đối và tăng conversion rate. Bao gồm script bán hàng và template message.",
    rating: 4.4,
    students: 3456,
    duration: "4 tuần",
    level: "Cơ bản",
    category: "Kinh doanh",
    tags: ["Bán hàng", "Online", "E-commerce", "Sales"],
    isFavorite: false,
  },
  {
    id: "28",
    title: "SEO Cơ Bản - Tối Ưu Website Lên Top Google",
    instructor: "Thầy Vương Văn O",
    price: 449000,
    originalPrice: 650000,
    image: "html.jpg",
    description: "Học SEO từ cơ bản, đưa website lên top Google một cách tự nhiên",
    fullDescription:
      "Khóa học SEO cơ bản và thực chiến. Học cách research keyword, tối ưu on-page, xây dựng backlink và đo lường hiệu quả. Bao gồm tools SEO miễn phí và checklist tối ưu.",
    rating: 4.6,
    students: 2789,
    duration: "7 tuần",
    level: "Cơ bản",
    category: "Marketing",
    tags: ["SEO", "Google", "Keyword", "Website"],
    isFavorite: false,
  },
]

export const PRICE_FILTERS = [
  { value: "all", label: "Tất cả mức giá" },
  { value: "under500k", label: "Dưới 500.000 VNĐ" },
  { value: "500k-1m", label: "500.000 - 1.000.000 VNĐ" },
  { value: "over1m", label: "Trên 1.000.000 VNĐ" },
]

// Thêm search suggestions
export const SEARCH_SUGGESTIONS = [
  "Tiếng Anh giao tiếp",
  "Lập trình web",
  "React JavaScript",
  "Digital Marketing",
  "Thiết kế đồ họa",
  "Python AI",
  "Kinh doanh khởi nghiệp",
  "Photoshop cơ bản",
  "SEO Marketing",
  "Node.js backend",
  "HTML CSS",
  "Excel cơ bản",
  "WordPress",
  "Canva design",
  "Video editing",
  "Tiếng Nhật N5",
  "Facebook Ads",
  "Google Ads",
  "Kế toán cơ bản",
  "Bán hàng online",
]
